environment:
  API_KEY: ${DO_API_KEY}
packages:
  - name: getTextFromDoc
    actions:
      - name: getTextFromDoc
        runtime: 'python:3.11'
        web: false
        webSecure: false
        limits: {
          timeout: 900000,
          memory: 512
        }
